// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class ColorSnipers_U_Resources
{
        public const string achievement_close_10_windows_in_level_2 = "CgkIs9vVhvQXEAIQCQ"; // <GPGSID>
        public const string achievement_near_miss_5_windows_in_level_1 = "CgkIs9vVhvQXEAIQAQ"; // <GPGSID>
        public const string achievement_close_70_windows_in_level_14 = "CgkIs9vVhvQXEAIQFQ"; // <GPGSID>
        public const string achievement_obtain_1_star_in_level_25 = "CgkIs9vVhvQXEAIQIA"; // <GPGSID>
        public const string achievement_miss_135_windows_in_level_27 = "CgkIs9vVhvQXEAIQIg"; // <GPGSID>
        public const string achievement_near_miss_all_150_windows_in_level_29 = "CgkIs9vVhvQXEAIQJA"; // <GPGSID>
        public const string achievement_miss_40_windows_in_level_8 = "CgkIs9vVhvQXEAIQDw"; // <GPGSID>
        public const string achievement_near_miss_23_windows_in_level_4 = "CgkIs9vVhvQXEAIQCw"; // <GPGSID>
        public const string achievement_close_60_windows_in_level_11 = "CgkIs9vVhvQXEAIQEg"; // <GPGSID>
        public const string achievement_near_miss_130_windows_in_level_26 = "CgkIs9vVhvQXEAIQIQ"; // <GPGSID>
        public const string achievement_near_miss_72_windows_in_level_15 = "CgkIs9vVhvQXEAIQFg"; // <GPGSID>
        public const string achievement_miss_105_windows_in_level__22 = "CgkIs9vVhvQXEAIQHQ"; // <GPGSID>
        public const string achievement_near_miss_all_95_windows_in_level_18 = "CgkIs9vVhvQXEAIQGQ"; // <GPGSID>
        public const string achievement_obtain_all_3_stars_in_in_level_30 = "CgkIs9vVhvQXEAIQJQ"; // <GPGSID>
        public const string achievement_near_miss_50_windows_in_level_10 = "CgkIs9vVhvQXEAIQEQ"; // <GPGSID>
        public const string achievement_obtain_2_stars_in_level_19 = "CgkIs9vVhvQXEAIQGg"; // <GPGSID>
        public const string achievement_close_30_windows_in_level_6 = "CgkIs9vVhvQXEAIQDQ"; // <GPGSID>
        public const string achievement_close_110_windows_in_level_23 = "CgkIs9vVhvQXEAIQHg"; // <GPGSID>
        public const string achievement_close_35_windows_in_level_7 = "CgkIs9vVhvQXEAIQDg"; // <GPGSID>
        public const string achievement_near_miss_99_windows_in_level_21 = "CgkIs9vVhvQXEAIQHA"; // <GPGSID>
        public const string achievement_miss_80_windows_in_level_16 = "CgkIs9vVhvQXEAIQFw"; // <GPGSID>
        public const string achievement_obtain_2_stars_in_level_24 = "CgkIs9vVhvQXEAIQHw"; // <GPGSID>
        public const string achievement_miss_15_windows_in_level_3 = "CgkIs9vVhvQXEAIQCg"; // <GPGSID>
        public const string achievement_close_100_windows_in_level_20 = "CgkIs9vVhvQXEAIQGw"; // <GPGSID>
        public const string achievement_obtain_1_star_in_level_13 = "CgkIs9vVhvQXEAIQFA"; // <GPGSID>
        public const string leaderboard_star_leaderboard = "CgkIs9vVhvQXEAIQJg"; // <GPGSID>
        public const string leaderboard_gem_leaderboard = "CgkIs9vVhvQXEAIQJw"; // <GPGSID>
        public const string achievement_miss_25_windows_in_level_5 = "CgkIs9vVhvQXEAIQDA"; // <GPGSID>
        public const string achievement_close_all_145_windows_in_level_28 = "CgkIs9vVhvQXEAIQIw"; // <GPGSID>
        public const string achievement_miss_60_windows_in_level_12 = "CgkIs9vVhvQXEAIQEw"; // <GPGSID>
        public const string achievement_obtain_2_stars_in_level_9 = "CgkIs9vVhvQXEAIQEA"; // <GPGSID>
        public const string achievement_close_81_windows_in_level_17 = "CgkIs9vVhvQXEAIQGA"; // <GPGSID>

}

